[versions]
dokka = "1.9.10"
jline = "3.21.0"
kotlin = "1.7.20" # Don't increase! We're intentionally using an old a version as possible for better compatibility
kotlinx-coroutines = "1.6.4"
kotlinx-serialization = "1.5.0"
kotter = "1.1.3-SNAPSHOT"
kover = "0.6.1"
nexus-publish = "1.3.0"
okhttp = "4.9.3"
truthish = "0.6.5"

[libraries]
jcip-annotations = { module = "net.jcip:jcip-annotations", version = "1.0" }
jline-terminal-core = { module = "org.jline:jline-terminal", version.ref = "jline" }
jline-terminal-jansi = { module = "org.jline:jline-terminal-jansi", version.ref = "jline" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
truthish = { module = "com.varabyte.truthish:truthish", version.ref = "truthish" }

[plugins]
jetbrains-dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotlinx-kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
nexus-publish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexus-publish" }
